baseURL: "https://chenyunsi.com/" # 暂时先这样写，后续部署时会改成你自己的网址
languageCode: "zh-cn"
title: "小石榴的世界" # 你的网站标题
theme: "PaperMod" # 使用PaperMod主题

# PaperMod 主题配置
params:
  title: "小石榴的世界"
  description: "记录小石榴的成长点滴" # 网站描述

# 启用评论等功能（可选，后续可配置）
outputs:
  home:
    - HTML
    - RSS
    - JSON
